# model definitions
nova_pro: &nova_pro "bedrock/us.amazon.nova-pro-v1:0"
titan_v2: &titan_v2 "bedrock/amazon.titan-embed-text-v2:0"
sat_3l_sm: &sat_3l_sm "sat-3l-sm"
gpt2: &gpt2 "gpt2"
opus_4_5: &opus_4_5 "bedrock/us.anthropic.claude-opus-4-5-20251101-v1:0"

dataset: "OURS_TEST"

# llm models
models:
  tokenizer: *gpt2
  segmenter: *sat_3l_sm
  embed: *titan_v2
  trip_extract: *opus_4_5
  eval_judge: *opus_4_5
  description_gen: *opus_4_5
  trim_model: *opus_4_5
  hgr: *opus_4_5
  # trip_extract: *nova_pro
  # eval_judge: *nova_pro
  # description_gen: *nova_pro

# maximum concurrent llm calls
llm_concurrency:
  embed: 10
  trip_extract: 8
  description_gen: 16

# llm call retry mechanism
llm_retry:
  initial_delay: 1
  max_attempts: 5

preprocess:
  # segmentation
  paragraph_thresh: 0.5 # SaT: bias for paragraph length
  min_chunk_tokens_thresh: 20 # minimum tokens before a segment is considered a chunk

  batch_token_target: 300 # pack chunks into a batch until we cross this threshold
  max_batch_items: 64 # maximum chunks to batch

  max_desc_length: 300 # max description length in tokens before condensing into a summary
  max_desc_chunks: 5 # max chunks to describe in a batch -- note -- seems redundant

leanrag:
  # build
  entity_batch_size: 32
  cluster_size: 20

  # retrieve
  max_top_chunks: 5