[project]
name = "x-rag"
version = "0.1.0"
requires-python = "==3.12.11"
dependencies = [
    "pydantic==2.11.7",
    "dspy==3.0.1",
    "openai==1.99.9", # Note: dspy 3.0.1 has a compatibility issue with openai 1.100.0: https://github.com/stanfordnlp/dspy/issues/8677
    "neo4j==5.28.2",
    "aioboto3==15.1.0",
    "wtpsplit[onnx-cpu]>=2.1.6",
    "wtpsplit[onnx-gpu]>=2.1.6",
    "python-dotenv",
    "scikit-learn",
    "aiolimiter",
    "datasets==2.18.0",
    "semhash",
    "inflect",
    "ijson>=3.4.0",
    "networkx>=3.6.1",
]

[project.optional-dependencies]
utils = [
    "pymupdf==1.26.3",
    "pymupdf4llm",
    "ijson==3.4.0"
]
leanrag = [
    "yake",
    "scikit-learn",
    "umap-learn; python_version < '3.12'"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "xrag"}

[tool.setuptools.packages.find]
where = ["xrag"]
