[project]
name = "x-rag"
version = "0.1.0"
requires-python = "==3.12.11"
dependencies = [
    "pydantic==2.11.7",
    "dspy==3.0.1",
    "openai==1.99.9", # Note: dspy 3.0.1 has a compatibility issue with openai 1.100.0: https://github.com/stanfordnlp/dspy/issues/8677
    "neo4j==5.28.2",
    "wtpsplit>=2.1.6",
    "scikit-learn"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
